### ISSUE TITLE
Flip animation doesn't work

### ISSUE THREAD

**Issue by MarcBruins** [MarcBruins/TTGSnackbar-Xamarin-iOS#1]
Couldn't find a replacement for 

```
 case .Flip:
            animationBlock = {
                self.layer.transform = CATransform3DMakeRotation(CGFloat(M_PI_2), 1, 0, 0)
            }
```

**Comment by IdresAhmed** [comment]
I ran into the same issue today. Maybe I am late, but this can help others in future.
Its Xamarin equivalent is: `CATransform3D.MakeRotation( myAngle, 1, 0, 0);`
