### ISSUE TITLE
An issue in the code

### ISSUE THREAD

**Issue by AkashDeepKaushik** [MarcBruins/TTGSnackbar-Xamarin-iOS#11]
In the main file of TTGSnakebar there is mistake in code at line 294 original code is 
"if (secondActionButton == null)
			{
				SecondActionText = String.Empty;
				secondActionButton.Hidden = true;
			}"
 but  if "secondActionButton" is null setting it's hidden property will cause a crash , I think it should be "SecondActionBlock" on the null check also because of this secondActionButton will never get hidden.
Please fix this and create a new package on nuget , right i have manually change it but it will be better to directly use nuget package.

**Comment by MarcBruins** [comment]
Thanks for the update. Feel free to make a PR that fixes this

**Comment by MarcBruins** [comment]
This is closed in #12
