### ISSUE TITLE
Separator always visible

### ISSUE THREAD

**Issue by LanderVe** [MarcBruins/TTGSnackbar-Xamarin-iOS#19]
In the most simple scenario:
```csharp
var snackbar = new TTGSnackbar(message);
snackbar.Show();
```
I always see a seperator, even though there's no action. I tried stuff like: 
```csharp
snackbar.SeperateView.Hidden = true;
```
But to no avail. Am I missing something? It appears you can't set the separator color like in the Swift version.

**Comment by MarcBruins** [comment]
That could very well be so. I'll have to take a look deeper look, but don't have the time right now. Feel free to make a PR to fix this issue.

**Comment by LanderVe** [comment]
I created a Pull Request to resolve the issue. It works and is very simple. Could you have a look?

**Comment by LanderVe** [comment]
By the way, for anyone looking to hide the separator even when you have an action, you can simply call
```csharp
snackbar.SeperateView.Alpha = 0;
```
or by changing the color
```csharp
snackbar.SeperateView.BackgroundColor = UIColor.Clear;
```
The first part was in the sample code of the project. The fix is still necessary tough because if you click to the right of the separator and don't have an action, you will get a NullReferenceException.

**Comment by LanderVe** [comment]
[this PR](https://github.com/MarcBruins/TTGSnackbar-Xamarin-iOS/pull/21) solved the problem. Big thanks to @valentingrigorean. @MarcBruins will you make a new Nuget Package?

**Comment by MarcBruins** [comment]
Created a new version, should be a out in a few minutes on nuget.
