### ISSUE TITLE
Setting BottomMargin crashes app

### ISSUE THREAD

**Issue by EmmanVazz** [MarcBruins/TTGSnackbar-Xamarin-iOS#5]
I am trying to set a bottom margin for the notification because I don't like where it is positioned. 

I do 
`var snackbar = new TTGSnackbar("Message", TTGSnackbarDuration.Short);`
`snackbar.BottomMargin = 50;`
`snackbar.Show();`

The crashe is in the setter
`set { _bottomMargin = value; bottomMarginConstraint.Constant = _bottomMargin; this.LayoutIfNeeded();`

bottomMarginConstraint is not initialized until you do .Show() causing the app to crash.

If I flip the Show() and the BottomMargin line, the `this.LayoutIfNeeded()` in the setter suppresses the notification.

Was there a different method you intended people to set the BottomMargin with?

Thanks,
Emmanuel

**Comment by MarcBruins** [comment]
Hi Emmanuel, this is defintely a bug! Everything should be configurable by using there public properties and it should not crash. Feel free to make a PR and I'll gladly merge it!

**Comment by EmmanVazz** [comment]
Should I just null check the MarginConstraints in the setter, easiest way to fix the crash? Not sure why you want to set the MarginConstraints as they are only initialized when you call Show() tho.

**Comment by EmmanVazz** [comment]
This [PR](https://github.com/MarcBruins/TTGSnackbar-Xamarin-iOS/pull/6) fixed this issue. Closing.
