### ISSUE TITLE
Show Snackbar at Top

### ISSUE THREAD

**Issue by ryanspiffy** [MarcBruins/TTGSnackbar-Xamarin-iOS#8]
The original library that this was ported from recently added the ability to show the snackbar at the top of the screen, adding a few new animation types and a topMargin property.  Could that be implemented here as well?  It may fix the issue with snackbars being hidden by the soft keyboard as well.

**Comment by eestein** [comment]
+1!

Gonna have to look for another library, since this one doesn't allow that :/

**Comment by MarcBruins** [comment]
Feel free to add it, its open source and nothing it stopping you from doing it yourself!

**Comment by eestein** [comment]
@MarcBruins sure, that's the beauty of it :) I just hope you didn't misunderstand my comment ;)
I was just sharing my frustration that this one that I already have installed an works, does not allow that. I'm already working on a custom view, though :)

**Comment by MarcBruins** [comment]
Sounds good! Shouldn't be to hard if you compare it to the original :)

**Comment by MarcBruins** [comment]
Are you still planning on adding this @eestein?

**Comment by eestein** [comment]
@MarcBruins hey, thanks for chiming... when I said I was working on a custom view I meant my own implementation, and that's what I did back then. If you'd like I can try to implement this feature on your lib. Let me fork it, take a look and I'll get back to you.

**Comment by MarcBruins** [comment]
Added see sample
